#!/usr/bin/awk -f
BEGIN {
    first_len = split(ARGV[1], first, ".")
    second_len = split(ARGV[2], second, ".")
    i = 1
    while (1) {
        # out of bounds
        if (i > first_len) {
            if (i > second_len) {
                print "EQ"
                exit
            } else {
                print "LT"
                exit
            }
        } else {
            if (i > second_len) {
                print "GT"
                exit
            }
        }

        # in bounds
        if (first[i] < second[i]) {
            print "LT"
            exit
        } else if (first[i] > second[i]) {
            print "GT"
            exit
        }
        i = i + 1
    }
}
